# Color scheme
[[plugins]]
repo = 'cocopon/pgmnt.vim'

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'

# Show git diff
[[plugins]]
repo = 'airblade/vim-gitgutter'

# File tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

# Nerdtree git plugin
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# Support parentheses, brackets, quotes, XML tags, and more 
[[plugins]]
repo = 'tpope/vim-surround'

# Lean & mean status/tabline for vim that's light as air.
[[plugins]]
repo = 'vim-airline/vim-airline'

# molokai color scheme
[[plugins]]
repo = 'tomasr/molokai'

# Auto close parentheses and repeat by dot dot dot...
[[plugins]]
repo = 'cohama/lexima.vim'

# Full path fuzzy file, buffer, mru, tag, ... finder
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# Window size controller
[[plugins]]
repo = 'simeji/winresizer'

# Go auto formatter
[[plugins]]
repo = 'mattn/vim-goimports'

# easymotion
[[plugins]]
repo = 'easymotion/vim-easymotion'
