name: Mac OS setup

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run install script
        run: |
          curl -fsSL https://raw.githubusercontent.com/kiyocy24/dotfiles/${{ github.ref_name }}/install.sh | zsh
