# This is a basic workflow to help you get started with Actions

name: macOS setup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: |
          curl -fsSL https://raw.githubusercontent.com/kiyocy24/dotfiles/${{ github.ref_name }}/install.sh | zsh
